import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/',
      '**/dist/',
      '**/*.d.ts',
      '**/coverage/',
      // Generated by `pnpm --filter @utexo/minimal-gateway generate:rln-types`.
      'packages/gateway/src/rln/openapi.ts',
      // Build output of the native mobile SDK (rustdoc emits .js under target/,
      // Gradle and SwiftPM emit reports). Gitignored, but flat config does not
      // read .gitignore, so `pnpm lint` after a local build would scan them.
      'rust-sdk/target/',
      'android/build/',
      'android/.gradle/',
      'apple/.build/',
      'apple/build/',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  prettier,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/explicit-module-boundary-types': 'off',
    },
  },
  {
    files: ['scripts/**/*.cjs'],
    languageOptions: {
      sourceType: 'commonjs',
      globals: {
        require: 'readonly',
        module: 'readonly',
        console: 'readonly',
        process: 'readonly',
        __dirname: 'readonly',
      },
    },
    rules: {
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  {
    files: ['**/scripts/**/*.mjs'],
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        URL: 'readonly',
      },
    },
  },
);
