// swift-tools-version: 5.9
import PackageDescription

// UTEXO minimal SDK for Apple platforms: the Swift bindings generated by
// ../scripts/generate_bindings.sh swift on top of the Rust core packaged by
// ../scripts/build_apple.sh as MinimalSdkFFI.xcframework. Run those two
// scripts (build_apple.sh runs both) before building this package.
//
// Deployment targets are the SDK's floor policy (see README.md): iOS 15 and
// macOS 12. build_apple.sh pins the same versions into the static libraries.

#if os(Linux)
// Host-only test aid, the same trick test/swift-e2e uses for the node: there
// is no XCFramework on Linux, so link the Rust cdylib from `cargo build
// --release` directly and expose the generated header through a
// systemLibrary target. This lets `swift test` run SmokeTests on a Linux
// box or runner. Never a shipping configuration; unsafeFlags also makes the
// package unusable as a dependency in this branch, which is intended.
let rustLibDir = Context.environment["UTEXO_MINIMAL_SDK_LIB_DIR"]
    ?? "\(Context.packageDirectory)/../rust-sdk/target/release"
let ffiTargets: [Target] = [
    .systemLibrary(name: "MinimalSdkFFI", path: "Sources/MinimalSdkFFI"),
]
let coreLinkerSettings: [LinkerSetting] = [
    .unsafeFlags(["-L", rustLibDir, "-Xlinker", "-rpath", "-Xlinker", rustLibDir]),
    .linkedLibrary("utexo_minimal_sdk"),
]
#else
let ffiTargets: [Target] = [
    .binaryTarget(name: "MinimalSdkFFI", path: "MinimalSdkFFI.xcframework"),
]
let coreLinkerSettings: [LinkerSetting] = []
#endif

let package = Package(
    name: "MinimalSdk",
    platforms: [
        .iOS(.v15),
        .macOS(.v12),
    ],
    products: [
        .library(name: "MinimalSdk", targets: ["MinimalSdk"]),
    ],
    targets: ffiTargets + [
        .target(
            name: "MinimalSdk",
            dependencies: ["MinimalSdkFFI"],
            path: "Sources/MinimalSdk",
            linkerSettings: coreLinkerSettings
        ),
        .testTarget(
            name: "MinimalSdkTests",
            dependencies: ["MinimalSdk"],
            path: "Tests/MinimalSdkTests"
        ),
    ]
)
